// 9회 문항별 주제 태그 + 신규 심화해설 (teacher.html의 QUESTION_TOPIC/TOPIC_NOTES에 병합됨)
const QUESTION_TOPIC_R9 = {
  "9": {
    1:"job_ethics_law",
    2:"job_ethics_law",
    3:"ward_safety_environment",
    4:"documentation",
    5:"body_systems_physio",
    6:"body_systems_physio",
    7:"drug_medication_admin",
    8:"drug_medication_admin",
    9:"nutrition_metabolism",
    10:"nutrition_metabolism",
    11:"dental_oral_care",
    12:"dental_oral_care",
    13:"oriental_medicine",
    14:"oriental_medicine",
    15:"therapeutic_communication",
    16:"drug_medication_admin",
    17:"restraint_positioning",
    18:"gi_surgery_nutrition_care",
    19:"seizure_care",
    20:"msk_arthritis_care",
    21:"hepatobiliary_care",
    22:"blood_management_law",
    23:"reproductive_physio",
    24:"obstetric_emergency",
    25:"obstetric_emergency",
    26:"vaccination",
    27:"newborn_assessment",
    28:"newborn_assessment",
    29:"newborn_assessment",
    30:"elderly_health_communication",
    31:"elderly_health_communication",
    32:"nutrition_metabolism",
    33:"burn_heat_cold_firstaid",
    34:"msk_arthritis_care",
    35:"eye_ear_care",
    36:"health_education",
    37:"health_education",
    38:"health_education",
    39:"health_education",
    40:"health_administration_system",
    41:"health_administration_system",
    42:"health_administration_system",
    43:"health_administration_system",
    44:"health_administration_system",
    45:"health_administration_system",
    46:"environmental_health",
    47:"infectious_disease_general",
    48:"environmental_health",
    49:"environmental_health",
    50:"occupational_health",
    51:"population_health_index",
    52:"infectious_disease_general",
    53:"infectious_disease_general",
    54:"infectious_disease_general",
    55:"infectious_disease_general",
    56:"population_health_index",
    57:"reproductive_physio",
    58:"maternal_child_health",
    59:"vaccination",
    60:"defense_mechanism",
    61:"community_visiting",
    62:"mental_health_care",
    63:"mental_health_care",
    64:"elderly_welfare_facility",
    65:"medical_law_records",
    66:"mental_health_law",
    67:"tuberculosis",
    68:"oral_health_law",
    69:"blood_management_law",
    70:"infectious_disease_grade",
    71:"ward_safety_environment",
    72:"vital_signs_assessment",
    73:"vital_signs_assessment",
    74:"vital_signs_assessment",
    75:"vital_signs_assessment",
    76:"vital_signs_assessment",
    77:"vital_signs_assessment",
    78:"vital_signs_assessment",
    79:"wound_dressing_sterile",
    80:"cpr_emergency",
    81:"basic_nursing_infection_control",
    82:"basic_nursing_infection_control",
    83:"basic_nursing_infection_control",
    84:"respiratory_care",
    85:"gi_exam_diagnostics",
    86:"basic_nursing_infection_control",
    87:"lab_specimen",
    88:"catheter_care",
    89:"respiratory_care",
    90:"restraint_positioning",
    91:"bedmaking_hygiene",
    92:"bedmaking_hygiene",
    93:"bedmaking_hygiene",
    94:"gi_surgery_nutrition_care",
    95:"gi_surgery_nutrition_care",
    96:"cpr_emergency",
    97:"gait_ambulation",
    98:"msk_arthritis_care",
    99:"perioperative_care",
    100:"skin_integument_aging",
    101:"restraint_positioning",
    102:"perioperative_care",
    103:"perioperative_care",
    104:"injection_practice",
    105:"catheter_care"
  }
};

const TOPIC_NOTES_R9 = {
  seizure_care: "경련 시에는 입에 어떤 것도 억지로 넣지 않고, 주변의 위험한 물건을 치워 신체 손상을 예방하는 것이 핵심입니다. 억지로 팔다리를 붙잡거나 신체보호대로 움직임을 막으면 오히려 골절·탈구 위험이 커지므로, '막지 말고 다치지 않게 주변만 정리한다'는 원칙을 강조해 주세요.",
  hepatobiliary_care: "황달은 혈액 내 담즙색소(빌리루빈) 농도가 비정상적으로 올라가 피부·점막이 노랗게 보이는 현상입니다. 원인에 따라 크게 세 가지로 나뉩니다: 간세포 자체 손상으로 담즙 대사가 안 되는 간세포성 황달, 적혈구가 과도하게 파괴되어 생기는 용혈성 황달, 담즙이 만들어진 후 배출길이 막히는 폐쇄성 황달. 각 유형의 원인과 증상을 헷갈리지 않도록 표로 정리해서 학습하면 도움이 됩니다."
};

if (typeof QUESTION_TOPIC !== 'undefined') {
  Object.keys(QUESTION_TOPIC_R9).forEach(function(r){
    QUESTION_TOPIC[r] = QUESTION_TOPIC_R9[r];
  });
}
if (typeof TOPIC_NOTES !== 'undefined') {
  Object.keys(TOPIC_NOTES_R9).forEach(function(k){
    TOPIC_NOTES[k] = TOPIC_NOTES_R9[k];
  });
}