// 7회 문항별 주제 태그 + 신규 심화해설 (teacher.html의 QUESTION_TOPIC/TOPIC_NOTES에 병합됨)
const QUESTION_TOPIC_R7 = {
  "7": {
    1:"job_ethics_law",
    2:"job_ethics_law",
    3:"basic_nursing_infection_control",
    4:"ward_safety_environment",
    5:"body_systems_physio",
    6:"body_systems_physio",
    7:"drug_medication_admin",
    8:"drug_medication_admin",
    9:"nutrition_metabolism",
    10:"nutrition_metabolism",
    11:"dental_oral_care",
    12:"dental_oral_care",
    13:"oriental_medicine",
    14:"oriental_medicine",
    15:"therapeutic_communication",
    16:"msk_arthritis_care",
    17:"msk_arthritis_care",
    18:"dental_oral_care",
    19:"gi_surgery_nutrition_care",
    20:"blood_transfusion_reaction",
    21:"chronic_disease_management",
    22:"child_infection_dehydration",
    23:"diagnostic_imaging_care",
    24:"obstetric_emergency",
    25:"maternal_child_health",
    26:"newborn_assessment",
    27:"child_development",
    28:"child_development",
    29:"premature_infant",
    30:"maslow_needs",
    31:"sleep_rest_care",
    32:"elderly_health_communication",
    33:"cpr_emergency",
    34:"burn_heat_cold_firstaid",
    35:"general_review",
    36:"health_education",
    37:"health_education",
    38:"health_education",
    39:"health_education",
    40:"health_administration_system",
    41:"health_administration_system",
    42:"health_administration_system",
    43:"occupational_health",
    44:"health_administration_system",
    45:"health_administration_system",
    46:"environmental_health",
    47:"environmental_health",
    48:"environmental_health",
    49:"environmental_health",
    50:"occupational_health",
    51:"disease_causation_factors",
    52:"disease_causation_factors",
    53:"infectious_disease_general",
    54:"tuberculosis",
    55:"chronic_disease_management",
    56:"population_health_index",
    57:"maternal_child_health",
    58:"maternal_child_health",
    59:"maternal_child_health",
    60:"defense_mechanism",
    61:"community_visiting",
    62:"community_visiting",
    63:"ltci",
    64:"elderly_welfare_facility",
    65:"medical_law_records",
    66:"mental_health_law",
    67:"tuberculosis",
    68:"oral_health_law",
    69:"blood_management_law",
    70:"infectious_disease_grade",
    71:"elimination_care",
    72:"sleep_rest_care",
    73:"skin_integument_aging",
    74:"vital_signs_assessment",
    75:"vital_signs_assessment",
    76:"vital_signs_assessment",
    77:"vital_signs_assessment",
    78:"injection_practice",
    79:"diagnostic_imaging_care",
    80:"medical_waste",
    81:"basic_nursing_infection_control",
    82:"wound_dressing_sterile",
    83:"wound_dressing_sterile",
    84:"tumor_oncology",
    85:"cpr_emergency",
    86:"gait_ambulation",
    87:"renal_care",
    88:"gi_exam_diagnostics",
    89:"vital_signs_assessment",
    90:"bedmaking_hygiene",
    91:"consciousness_level",
    92:"dysphagia_feeding",
    93:"elimination_care",
    94:"renal_care",
    95:"perioperative_care",
    96:"cpr_emergency",
    97:"immobility_complications",
    98:"msk_arthritis_care",
    99:"gait_ambulation",
    100:"burn_heat_cold_firstaid",
    101:"bandage",
    102:"perioperative_care",
    103:"oral_medication_practice",
    104:"injection_practice",
    105:"hospice_endoflife"
  }
};

const TOPIC_NOTES_R7 = {
  blood_transfusion_reaction: "수혈 중 발열·오한·호흡곤란·요통·두드러기 등 부작용 징후가 나타나면 즉시 수혈을 중지하고 생리식염수 라인을 유지한 채 간호사·의사에게 보고합니다. 학생들에게는 '이상 증상 발견 시 가장 먼저 할 일 = 즉시 중지'라는 순서를 강조해 주세요.",
  diagnostic_imaging_care: "X선 등 방사선 촬영은 태아 기형 위험이 가장 큰 임신 초기(12주 이내)에 절대 금기이며, 검사 전에는 금속물질(목걸이, 귀걸이, 벨트 등)을 제거해야 정확한 영상을 얻을 수 있습니다. 검사 종류별로 준비사항(금식, 관장, 금속 제거 등)이 다르다는 점을 함께 짚어주면 좋습니다.",
  chronic_disease_management: "고혈압·동맥경화증 등 만성질환 관리의 핵심은 처방된 약물을 꾸준히 복용하고 저지방·저염식이, 금연, 적절한 운동을 병행하는 생활습관 관리입니다. 절대안정이나 급격한 온도 변화(냉·온욕)는 오히려 혈관에 부담을 줄 수 있어 피해야 한다는 점을 강조해 주세요.",
  sleep_rest_care: "가장 깊은 수면 단계인 비렘수면(NREM) 4단계에서 성장호르몬 분비와 신체 회복이 가장 활발합니다. 입원 환자의 숙면을 돕기 위해서는 취침 전 등마사지, 어두운 조명, 최소한의 자극이 필요하며, 장시간 낮잠이나 취침 전 고강도 운동은 오히려 밤잠을 방해합니다.",
  immobility_complications: "장기간 움직이지 못하는 부동 상태는 전신에 다양한 악영향을 줍니다: 장운동 저하(변비), 골칼슘 유출(고칼슘혈증), 기립성 저혈압, 요정체, 관절 구축, 욕창 등이 대표적입니다. '무엇이 증가하고 무엇이 감소하는지'를 헷갈리지 않도록 표로 정리해서 학습하면 도움이 됩니다."
};

if (typeof QUESTION_TOPIC !== 'undefined') {
  Object.keys(QUESTION_TOPIC_R7).forEach(function(r){
    QUESTION_TOPIC[r] = QUESTION_TOPIC_R7[r];
  });
}
if (typeof TOPIC_NOTES !== 'undefined') {
  Object.keys(TOPIC_NOTES_R7).forEach(function(k){
    TOPIC_NOTES[k] = TOPIC_NOTES_R7[k];
  });
}