// 8회 문항별 주제 태그 + 신규 심화해설 (teacher.html의 QUESTION_TOPIC/TOPIC_NOTES에 병합됨)
const QUESTION_TOPIC_R8 = {
  "8": {
    1:"job_ethics_law",
    2:"job_ethics_law",
    3:"medical_waste",
    4:"ward_safety_environment",
    5:"body_systems_physio",
    6:"body_systems_physio",
    7:"drug_medication_admin",
    8:"drug_medication_admin",
    9:"nutrition_metabolism",
    10:"nutrition_metabolism",
    11:"dental_oral_care",
    12:"dental_oral_care",
    13:"oriental_medicine",
    14:"immunity_types",
    15:"msk_arthritis_care",
    16:"diagnostic_imaging_care",
    17:"allergy_anaphylaxis_care",
    18:"gi_surgery_nutrition_care",
    19:"gi_surgery_nutrition_care",
    20:"chronic_disease_management",
    21:"reproductive_physio",
    22:"diabetes_care",
    23:"obstetric_emergency",
    24:"obstetric_emergency",
    25:"breastfeeding",
    26:"newborn_assessment",
    27:"maternal_child_health",
    28:"child_development",
    29:"child_infection_dehydration",
    30:"skin_integument_aging",
    31:"gi_surgery_nutrition_care",
    32:"incontinence_care",
    33:"cpr_emergency",
    34:"eye_ear_care",
    35:"cpr_emergency",
    36:"health_education",
    37:"therapeutic_communication",
    38:"health_education",
    39:"health_education",
    40:"health_administration_system",
    41:"maternal_child_health",
    42:"health_administration_system",
    43:"health_administration_system",
    44:"ltci",
    45:"health_administration_system",
    46:"environmental_health",
    47:"environmental_health",
    48:"environmental_health",
    49:"environmental_health",
    50:"occupational_health",
    51:"disease_causation_factors",
    52:"community_visiting",
    53:"vaccination",
    54:"infectious_disease_general",
    55:"infectious_disease_general",
    56:"population_health_index",
    57:"maternal_child_health",
    58:"newborn_assessment",
    59:"vaccination",
    60:"defense_mechanism",
    61:"community_visiting",
    62:"community_visiting",
    63:"mental_health_care",
    64:"community_visiting",
    65:"medical_law_records",
    66:"mental_health_law",
    67:"tuberculosis",
    68:"oral_health_law",
    69:"blood_management_law",
    70:"infectious_disease_grade",
    71:"therapeutic_communication",
    72:"reproductive_physio",
    73:"bedmaking_hygiene",
    74:"vital_signs_assessment",
    75:"basic_nursing_infection_control",
    76:"catheter_care",
    77:"basic_nursing_infection_control",
    78:"restraint_positioning",
    79:"basic_nursing_infection_control",
    80:"wound_dressing_sterile",
    81:"wound_dressing_sterile",
    82:"wound_dressing_sterile",
    83:"isolation_precautions",
    84:"gi_exam_diagnostics",
    85:"dental_oral_care",
    86:"gi_surgery_nutrition_care",
    87:"elimination_care",
    88:"catheter_care",
    89:"eye_ear_care",
    90:"skin_integument_aging",
    91:"bedmaking_hygiene",
    92:"catheter_care",
    93:"msk_arthritis_care",
    94:"gait_ambulation",
    95:"burn_heat_cold_firstaid",
    96:"cpr_emergency",
    97:"gi_surgery_nutrition_care",
    98:"oxygen_therapy",
    99:"perioperative_care",
    100:"perioperative_care",
    101:"perioperative_care",
    102:"injection_practice",
    103:"drug_medication_admin",
    104:"injection_practice",
    105:"therapeutic_communication"
  }
};

const TOPIC_NOTES_R8 = {
  allergy_anaphylaxis_care: "특정 음식(땅콩 등 견과류, 갑각류 등)이나 약물 섭취 후 몇 분 내로 호흡곤란, 두드러기, 혈압저하, 어지러움 등이 나타나면 급성중증과민증(아나필락시스)을 의심해야 합니다. 매우 빠르게 진행되어 생명을 위협할 수 있으므로 즉시 응급처치와 의료진 보고가 필요하다는 점을 강조해 주세요.",
  incontinence_care: "실금이 있는 환자를 돌볼 때는 회음부를 요도(앞)에서 항문(뒤) 방향으로 닦아 감염을 예방하고, 협조가 불가능한 환자는 측위로 돌려 눕힌 후 기저귀를 교환하며, 사용한 기저귀는 안쪽면이 보이지 않게 말아서 버려야 합니다. 하나하나의 절차가 위생·감염 예방과 직결된다는 점을 짚어주면 좋습니다.",
  isolation_precautions: "격리에는 두 가지 방향이 있습니다: 전파성 질환(결핵, VRE, 홍역, 수두 등)은 다른 사람에게 옮기지 않기 위한 '일반 격리'가 필요하고, 반대로 면역이 저하된 환자(장기이식, 항암치료 등)는 외부 감염으로부터 보호하기 위한 '역격리(보호격리)'가 필요합니다. 두 개념이 반대 방향이라는 점을 헷갈리지 않도록 짚어주세요."
};

if (typeof QUESTION_TOPIC !== 'undefined') {
  Object.keys(QUESTION_TOPIC_R8).forEach(function(r){
    QUESTION_TOPIC[r] = QUESTION_TOPIC_R8[r];
  });
}
if (typeof TOPIC_NOTES !== 'undefined') {
  Object.keys(TOPIC_NOTES_R8).forEach(function(k){
    TOPIC_NOTES[k] = TOPIC_NOTES_R8[k];
  });
}