// 5회·6회 문항별 주제 태그 + 신규 심화해설(TOPIC_NOTES) 병합 파일
const QUESTION_TOPIC_R5_6 = {
  "5": {
    "1": "job_ethics_law",
    "2": "job_ethics_law",
    "3": "vital_signs_assessment",
    "4": "medical_waste",
    "5": "body_systems_physio",
    "6": "body_systems_physio",
    "7": "drug_medication_admin",
    "8": "drug_medication_admin",
    "9": "nutrition_metabolism",
    "10": "obstetric_emergency",
    "11": "dental_oral_care",
    "12": "dental_oral_care",
    "13": "oriental_medicine",
    "14": "oriental_medicine",
    "15": "elderly_health_communication",
    "16": "tumor_oncology",
    "17": "amputation_phantom_care",
    "18": "tumor_oncology",
    "19": "gi_surgery_nutrition_care",
    "20": "respiratory_care",
    "21": "skeletal_muscle_blood",
    "22": "renal_care",
    "23": "reproductive_physio",
    "24": "obstetric_emergency",
    "25": "obstetric_emergency",
    "26": "child_development",
    "27": "breastfeeding",
    "28": "child_infection_dehydration",
    "29": "child_infection_dehydration",
    "30": "elderly_health_communication",
    "31": "elderly_health_communication",
    "32": "elderly_health_communication",
    "33": "burn_heat_cold_firstaid",
    "34": "consciousness_level",
    "35": "burn_heat_cold_firstaid",
    "36": "health_education",
    "37": "health_education",
    "38": "health_education",
    "39": "health_education",
    "40": "health_administration_system",
    "41": "health_administration_system",
    "42": "health_administration_system",
    "43": "health_administration_system",
    "44": "health_administration_system",
    "45": "health_administration_system",
    "46": "environmental_health",
    "47": "environmental_health",
    "48": "environmental_health",
    "49": "environmental_health",
    "50": "occupational_health",
    "51": "health_education",
    "52": "disease_causation_factors",
    "53": "infectious_disease_general",
    "54": "tuberculosis",
    "55": "infectious_disease_general",
    "56": "population_health_index",
    "57": "maternal_child_health",
    "58": "maternal_child_health",
    "59": "infectious_disease_grade",
    "60": "community_visiting",
    "61": "mental_health_care",
    "62": "therapeutic_communication",
    "63": "ltci",
    "64": "ltci",
    "65": "medical_law_records",
    "66": "mental_health_law",
    "67": "tuberculosis",
    "68": "oral_health_law",
    "69": "blood_management_law",
    "70": "infectious_disease_grade",
    "71": "admission_transfer",
    "72": "vital_signs_assessment",
    "73": "vital_signs_assessment",
    "74": "vital_signs_assessment",
    "75": "medical_waste",
    "76": "basic_nursing_infection_control",
    "77": "basic_nursing_infection_control",
    "78": "basic_nursing_infection_control",
    "79": "restraint_positioning",
    "80": "basic_nursing_infection_control",
    "81": "lab_specimen",
    "82": "gi_exam_diagnostics",
    "83": "restraint_positioning",
    "84": "bedmaking_hygiene",
    "85": "bedmaking_hygiene",
    "86": "bedmaking_hygiene",
    "87": "dental_oral_care",
    "88": "burn_heat_cold_firstaid",
    "89": "restraint_positioning",
    "90": "ward_safety_environment",
    "91": "burn_heat_cold_firstaid",
    "92": "elimination_care",
    "93": "tracheostomy_airway",
    "94": "oxygen_therapy",
    "95": "wound_dressing_sterile",
    "96": "cpr_emergency",
    "97": "wound_dressing_sterile",
    "98": "bedmaking_hygiene",
    "99": "bandage",
    "100": "restraint_positioning",
    "101": "msk_arthritis_care",
    "102": "perioperative_care",
    "103": "perioperative_care",
    "104": "hospice_endoflife",
    "105": "eye_ear_care"
  },
  "6": {
    "1": "ward_safety_environment",
    "2": "job_ethics_law",
    "3": "basic_nursing_infection_control",
    "4": "restraint_positioning",
    "5": "body_systems_physio",
    "6": "body_systems_physio",
    "7": "drug_medication_admin",
    "8": "drug_medication_admin",
    "9": "nutrition_metabolism",
    "10": "body_systems_physio",
    "11": "dental_oral_care",
    "12": "dental_oral_care",
    "13": "oriental_medicine",
    "14": "oriental_medicine",
    "15": "elderly_health_communication",
    "16": "gi_exam_diagnostics",
    "17": "tumor_oncology",
    "18": "gi_surgery_nutrition_care",
    "19": "respiratory_care",
    "20": "cardiovascular_care",
    "21": "stroke_recognition",
    "22": "eye_ear_care",
    "23": "reproductive_physio",
    "24": "obstetric_emergency",
    "25": "obstetric_emergency",
    "26": "child_development",
    "27": "child_development",
    "28": "child_abuse_types",
    "29": "infectious_disease_general",
    "30": "elderly_health_communication",
    "31": "bedmaking_hygiene",
    "32": "elimination_care",
    "33": "burn_heat_cold_firstaid",
    "34": "amputation_phantom_care",
    "35": "burn_heat_cold_firstaid",
    "36": "diabetes_care",
    "37": "health_education",
    "38": "community_visiting",
    "39": "health_education",
    "40": "health_administration_system",
    "41": "health_administration_system",
    "42": "health_administration_system",
    "43": "health_administration_system",
    "44": "health_administration_system",
    "45": "health_administration_system",
    "46": "environmental_health",
    "47": "environmental_health",
    "48": "environmental_health",
    "49": "environmental_health",
    "50": "occupational_health",
    "51": "immunity_types",
    "52": "infectious_disease_general",
    "53": "infectious_disease_general",
    "54": "infectious_disease_general",
    "55": "disease_prevention_levels",
    "56": "population_health_index",
    "57": "maternal_child_health",
    "58": "population_health_index",
    "59": "vaccination",
    "60": "community_visiting",
    "61": "community_visiting",
    "62": "defense_mechanism",
    "63": "ltci",
    "64": "ltci",
    "65": "medical_law_records",
    "66": "mental_health_law",
    "67": "tuberculosis",
    "68": "oral_health_law",
    "69": "blood_management_law",
    "70": "infectious_disease_grade",
    "71": "basic_nursing_infection_control",
    "72": "ward_safety_environment",
    "73": "vital_signs_assessment",
    "74": "vital_signs_assessment",
    "75": "respiratory_care",
    "76": "bedmaking_hygiene",
    "77": "basic_nursing_infection_control",
    "78": "basic_nursing_infection_control",
    "79": "restraint_positioning",
    "80": "basic_nursing_infection_control",
    "81": "gi_exam_diagnostics",
    "82": "gi_exam_diagnostics",
    "83": "bedmaking_hygiene",
    "84": "bedmaking_hygiene",
    "85": "restraint_positioning",
    "86": "gait_ambulation",
    "87": "consciousness_level",
    "88": "gait_ambulation",
    "89": "restraint_positioning",
    "90": "gi_surgery_nutrition_care",
    "91": "oxygen_therapy",
    "92": "catheter_care",
    "93": "catheter_care",
    "94": "restraint_positioning",
    "95": "bedmaking_hygiene",
    "96": "cpr_emergency",
    "97": "injection_practice",
    "98": "perioperative_care",
    "99": "perioperative_care",
    "100": "perioperative_care",
    "101": "wound_dressing_sterile",
    "102": "reproductive_physio",
    "103": "oral_medication_practice",
    "104": "therapeutic_communication",
    "105": "hospice_endoflife"
  }
};

// 5회·6회에서 새로 등장한 주제 키에 대한 심화해설 (기존 TOPIC_NOTES에 병합됨)
const TOPIC_NOTES_R5_6 = {
  "body_systems_physio": "장기별 생리 기능은 짝을 지어 암기한다: 췌장(랑게르한스섬)은 인슐린(혈당↓)·글루카곤(혈당↑)을 분비하고 동시에 트립신·아밀레이스 등 소화효소도 분비하는 이중 기능 장기이다. 심장은 좌심실 벽이 가장 두껍고 압력이 가장 높다(온몸으로 혈액을 뿜어내야 하므로). 체온조절 중추는 간뇌의 시상하부이며, 단백질 대사산물인 요소·요산·크레아티닌은 신장을 통해 소변으로 배출된다.",
  "amputation_phantom_care": "절단 관련 문항은 절단 후 통증과 절단부위 보관법 두 가지로 나뉜다. 환상지통(환상통)은 이미 절단된 부위가 아직 있는 것처럼 느껴지는 통증으로, 신경계가 남아있는 신경 신호를 잘못 해석해 발생한다. 외상으로 신체 일부가 절단되었을 때는 절단부위를 깨끗한 거즈로 감싸 비닐에 밀봉한 뒤, 얼음에 직접 닿지 않도록 얼음을 채운 용기(아이스박스)에 넣어 이송해야 조직 손상 없이 재접합 가능성을 높일 수 있다.",
  "therapeutic_communication": "치료적 의사소통에서는 개방형 질문과 폐쇄형 질문을 구분하는 것이 핵심이다. 개방형 질문은 '어떻게 생각하세요?'처럼 대상자가 자유롭게 설명하도록 유도하고, 폐쇄형 질문은 '~한 적이 있나요?'처럼 예/아니오로 답하는 질문이다. 반영(reflecting)은 환자가 한 말을 그대로 되비추어 표현해 스스로 생각을 정리하게 돕는 기법으로, 성급한 조언이나 해결책 제시보다 환자의 말을 인정하고 격려하는 반응이 치료적이다.",
  "stroke_recognition": "뇌졸중(중풍)은 골든타임 내 신속한 인지가 예후를 좌우하므로 F.A.S.T(Face 안면마비, Arm 팔 마비, Speech 언어장애, Time 시간)와 같은 신속 선별법을 암기해둔다. 손을 위로 들어보게 하거나 웃어보게 하거나 침을 흘리는지 관찰하는 것은 각각 편측 근력 저하, 안면 비대칭, 연하·구음 장애를 확인하는 방법으로 뇌졸중을 의심하는 대표적인 방법이다.",
  "eye_ear_care": "안과 관련 처치는 목적과 방향을 짝지어 암기한다. 안약은 각막을 자극하지 않도록 하부결막낭의 중앙에 점적하며, 눈의 분비물은 감염 확산을 막기 위해 안쪽(비루관 쪽)에서 바깥쪽으로 닦아낸다. 백내장·녹내장 수술 후에는 안압 상승을 유발하는 행동(기침, 코풀기, 무거운 물건 들기, 고개 숙이기)을 피해야 한다는 공통 원칙도 함께 정리해두면 좋다.",
  "cardiovascular_care": "고혈압의 90% 이상은 원인이 명확하지 않은 본태성(1차성) 고혈압이며, 이차성 고혈압은 신장질환 등 다른 질환이 원인인 소수의 경우이다. 치료에는 저염·저지방 식이, 체중 조절과 함께 이뇨제·베타차단제 등 약물요법이 병행되며, 혈압이 조절되어도 약을 임의로 중단하면 재발 위험이 크므로 꾸준한 복용이 중요하다는 점을 강조해야 한다.",
  "gait_ambulation": "목발·보행기 보행법은 체중 부하 가능 여부에 따라 구분한다. 한쪽 다리에 체중을 실을 수 없는 3점 보행은 양쪽 목발과 아픈 다리를 먼저 함께 내밀고, 이어서 건강한 다리를 내딛는 순서로 진행한다. 보행기는 환자가 먼저 보행기를 살짝 들어 앞으로 옮긴 뒤 그 안으로 바른 자세로 걸어 들어가야 하며, 몸을 지나치게 앞으로 기울이면 넘어질 위험이 있다.",
  "child_abuse_types": "아동학대는 유형별 특징으로 구분해 암기한다. 신체적 학대는 물리적 손상을 입히는 행위, 정서적 학대는 언어폭력·모욕·위협 등 정서적 위해, 성적 학대는 성적 행위 강요나 노출, 유기는 아동을 버리고 돌보지 않는 것이다. 방임은 옷차림이 지저분하거나 계절에 맞지 않고 학교에 보내지 않는 등 기본적인 의식주·교육·의료를 제공하지 않고 방치하는 것으로, 적극적 학대보다 발견이 늦어지기 쉬운 유형이다."
};

if (typeof QUESTION_TOPIC !== 'undefined') {
  Object.keys(QUESTION_TOPIC_R5_6).forEach(function(r){
    QUESTION_TOPIC[r] = QUESTION_TOPIC_R5_6[r];
  });
}
if (typeof TOPIC_NOTES !== 'undefined') {
  Object.keys(TOPIC_NOTES_R5_6).forEach(function(k){
    TOPIC_NOTES[k] = TOPIC_NOTES_R5_6[k];
  });
}