// 10회 문항별 주제 태그 + 신규 심화해설 (teacher.html의 QUESTION_TOPIC/TOPIC_NOTES에 병합됨)
const QUESTION_TOPIC_R10 = {
  "10": {
    1:"job_ethics_law",
    2:"ward_safety_environment",
    3:"ward_safety_environment",
    4:"documentation",
    5:"body_systems_physio",
    6:"body_systems_physio",
    7:"drug_medication_admin",
    8:"drug_medication_admin",
    9:"gi_surgery_nutrition_care",
    10:"gi_surgery_nutrition_care",
    11:"dental_oral_care",
    12:"dental_oral_care",
    13:"oriental_medicine",
    14:"oriental_medicine",
    15:"therapeutic_communication",
    16:"general_review",
    17:"gi_surgery_nutrition_care",
    18:"ostomy_care",
    19:"tumor_oncology",
    20:"diabetes_care",
    21:"respiratory_care",
    22:"eye_ear_care",
    23:"obstetric_emergency",
    24:"reproductive_physio",
    25:"obstetric_emergency",
    26:"respiratory_care",
    27:"child_development",
    28:"newborn_assessment",
    29:"tumor_oncology",
    30:"skin_integument_aging",
    31:"elderly_health_communication",
    32:"therapeutic_communication",
    33:"msk_arthritis_care",
    34:"burn_heat_cold_firstaid",
    35:"cpr_emergency",
    36:"health_education",
    37:"health_education",
    38:"health_education",
    39:"health_education",
    40:"health_administration_system",
    41:"health_administration_system",
    42:"health_administration_system",
    43:"health_administration_system",
    44:"health_administration_system",
    45:"health_administration_system",
    46:"environmental_health",
    47:"environmental_health",
    48:"environmental_health",
    49:"environmental_health",
    50:"occupational_health",
    51:"tumor_oncology",
    52:"infectious_disease_general",
    53:"immunity_types",
    54:"infectious_disease_general",
    55:"disease_prevention_levels",
    56:"population_health_index",
    57:"maternal_child_health",
    58:"maternal_child_health",
    59:"vaccination",
    60:"defense_mechanism",
    61:"community_visiting",
    62:"mental_health_care",
    63:"ltci",
    64:"ltci",
    65:"medical_law_records",
    66:"mental_health_law",
    67:"tuberculosis",
    68:"oral_health_law",
    69:"blood_management_law",
    70:"infectious_disease_grade",
    71:"therapeutic_communication",
    72:"vital_signs_assessment",
    73:"medical_waste",
    74:"vital_signs_assessment",
    75:"isolation_precautions",
    76:"vital_signs_assessment",
    77:"wound_dressing_sterile",
    78:"basic_nursing_infection_control",
    79:"dental_oral_care",
    80:"bedmaking_hygiene",
    81:"diabetes_care",
    82:"restraint_positioning",
    83:"oxygen_therapy",
    84:"incontinence_care",
    85:"gi_surgery_nutrition_care",
    86:"body_mechanics_safety",
    87:"eye_ear_care",
    88:"gait_ambulation",
    89:"body_mechanics_safety",
    90:"intake_output_monitoring",
    91:"catheter_care",
    92:"tracheostomy_airway",
    93:"catheter_care",
    94:"elimination_care",
    95:"perioperative_care",
    96:"cpr_emergency",
    97:"respiratory_care",
    98:"perioperative_care",
    99:"wound_dressing_sterile",
    100:"wound_dressing_sterile",
    101:"oral_medication_practice",
    102:"injection_practice",
    103:"injection_practice",
    104:"basic_nursing_infection_control",
    105:"hospice_endoflife"
  }
};

const TOPIC_NOTES_R10 = {
  body_mechanics_safety: "환자를 옮기거나 이동시킬 때는 작은 근육이 아니라 큰 근육(다리, 팔)을 사용하고, 허리는 펴고 무릎을 굽혀 다리 힘으로 들어 올려야 허리 손상을 예방할 수 있습니다. 또한 두 발을 벌려 지지 기저면을 넓히고, 이동할 방향을 마주 보고 서서 환자와 가까운 거리를 유지하는 것이 안전한 신체 역학의 기본 원칙입니다.",
  intake_output_monitoring: "섭취량(intake)에는 마시거나 먹은 물, 음료, 수액, 위관 영양액 등이 포함되고, 배설량(output)에는 소변, 구토물, 배액량, 설사 등이 포함됩니다. 가글 후 뱉어낸 물처럼 실제로 체내에 흡수되지 않은 것은 섭취량에도 배설량에도 포함하지 않는다는 점을 헷갈리지 않도록 짚어주면 좋습니다."
};

if (typeof QUESTION_TOPIC !== 'undefined') {
  Object.keys(QUESTION_TOPIC_R10).forEach(function(r){
    QUESTION_TOPIC[r] = QUESTION_TOPIC_R10[r];
  });
}
if (typeof TOPIC_NOTES !== 'undefined') {
  Object.keys(TOPIC_NOTES_R10).forEach(function(k){
    TOPIC_NOTES[k] = TOPIC_NOTES_R10[k];
  });
}